name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >
            --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0' 
            --retry-count 3
            --wait-time 2s
            --exclude https://ieeexplore.ieee.org/abstract/document/10021101
            --exclude https://ieeexplore.ieee.org/abstract/document/10438925
            --exclude https://ieeexplore.ieee.org/abstract/document/10494442
            --exclude https://ieeexplore.ieee.org/abstract/document/10214895
            --exclude https://ieeexplore.ieee.org/abstract/document/10279316
            --exclude https://ieeexplore.ieee.org/abstract/document/10436841
            --exclude-path README.md
            --exclude-path _pages/404.md
            --exclude-path _pages/blog.md
            --exclude-path _posts/2018-12-22-distill.md
            --exclude-path _posts/2023-04-24-videos.md
            --verbose
            --no-progress './**/*.md' './**/*.html'
